In [1]:
import pandas as pd
import numpy as np

In [2]:
true = pd.read_csv('True.csv')
fake = pd.read_csv('Fake.csv')

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
true['label'] = 1
fake['label'] = 0

In [5]:
true.head

<bound method NDFrame.head of                                                    title  \
0      As U.S. budget fight looms, Republicans flip t...
1      U.S. military to accept transgender recruits o...
2      Senior U.S. Republican senator: 'Let Mr. Muell...
3      FBI Russia probe helped by Australian diplomat...
4      Trump wants Postal Service to charge 'much mor...
...                                                  ...
21412  'Fully committed' NATO backs new U.S. approach...
21413  LexisNexis withdrew two products from Chinese ...
21414  Minsk cultural hub becomes haven from authorities
21415  Vatican upbeat on possibility of Pope Francis ...
21416  Indonesia to buy $1.14 billion worth of Russia...

                                                    text       subject  \
0      WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1      WASHINGTON (Reuters) - Transgender people will...  politicsNews
2      WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3      WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4      SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews
...                                                  ...           ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...     worldnews
21413  LONDON (Reuters) - LexisNexis, a provider of l...     worldnews
21414  MINSK (Reuters) - In the shadow of disused Sov...     worldnews
21415  MOSCOW (Reuters) - Vatican Secretary of State ...     worldnews
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...     worldnews

                     date  label
0      December 31, 2017       1
1      December 29, 2017       1
2      December 31, 2017       1
3      December 30, 2017       1
4      December 29, 2017       1
...                   ...    ...
21412    August 22, 2017       1
21413    August 22, 2017       1
21414    August 22, 2017       1
21415    August 22, 2017       1
21416    August 22, 2017       1

[21417 rows x 5 columns]>

In [6]:
news = pd.concat([fake, true], axis = 0)

In [7]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [8]:
news = news.drop(['title','subject','date'], axis=1)

In [9]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [10]:
# reshuffle data 
news = news.sample(frac = 1)

In [11]:
news.head()

                                                    text  label
18452  DERA ISMAIL KHAN, Pakistan (Reuters) - A Pakis...      1
213    Every once in a while, the perfect pun comes a...      0
319    WASHINGTON (Reuters) - The chief Republican ta...      1
19063  It s good to know that illegal aliens, potenti...      0
4827    WASHINGTON (Reuters) - U.S. President Donald ...      1

In [12]:
news.reset_index(inplace=True) #reset index

In [13]:
news.head()

   index                                               text  label
0  18452  DERA ISMAIL KHAN, Pakistan (Reuters) - A Pakis...      1
1    213  Every once in a while, the perfect pun comes a...      0
2    319  WASHINGTON (Reuters) - The chief Republican ta...      1
3  19063  It s good to know that illegal aliens, potenti...      0
4   4827   WASHINGTON (Reuters) - U.S. President Donald ...      1

In [14]:
news.drop(['index'], axis=1, inplace = True)

In [15]:
news.head(10)

                                                text  label
0  DERA ISMAIL KHAN, Pakistan (Reuters) - A Pakis...      1
1  Every once in a while, the perfect pun comes a...      0
2  WASHINGTON (Reuters) - The chief Republican ta...      1
3  It s good to know that illegal aliens, potenti...      0
4   WASHINGTON (Reuters) - U.S. President Donald ...      1
5  WASHINGTON (Reuters) - The chairman of the U.S...      1
6  BRUSSELS (Reuters) - NATO promised on Wednesda...      1
7   The Nuclear Deal  became a Republican talking...      0
8  After reporter and model, Leeann Tweeden accus...      0
9  21st Century Wire says With the ongoing hyster...      0

In [16]:
# till here (the above code) we have done the data preprocessing part 

# now comes the feature extraction part

In [17]:
import re
import string

In [18]:
def textProcessing(text):
    # Convert text to lowercase
    text = text.lower()
    
    # Remove text within square brackets
    text = re.sub(r'\[.*?\]', '', text)
    
    # Replace non-word characters (excluding spaces) with a space
    text = re.sub(r'\W', ' ', text)
    
    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    # Remove punctuation
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    
    # Remove numeric characters
    text = re.sub(r'\d+', '', text)
    
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

In [19]:
news['text'] = news['text'].apply(textProcessing)

In [20]:
news['text']

0        dera ismail khan pakistan reuters a pakistani ...
1        every once in a while the perfect pun comes al...
2        washington reuters the chief republican tax wr...
3        it s good to know that illegal aliens potentia...
4        washington reuters u s president donald trump ...
                               ...
44893    moscow reuters russian deputy foreign minister...
44894    belfast reuters the british government on mond...
44895    geneva reuters the world health organization w...
44896    chicago reuters any hope for a break in illino...
44897    long overdue in a closed door meeting with jew...
Name: text, Length: 44898, dtype: object

In [21]:
x = news['text']
y = news['label']

In [22]:
x

0        dera ismail khan pakistan reuters a pakistani ...
1        every once in a while the perfect pun comes al...
2        washington reuters the chief republican tax wr...
3        it s good to know that illegal aliens potentia...
4        washington reuters u s president donald trump ...
                               ...
44893    moscow reuters russian deputy foreign minister...
44894    belfast reuters the british government on mond...
44895    geneva reuters the world health organization w...
44896    chicago reuters any hope for a break in illino...
44897    long overdue in a closed door meeting with jew...
Name: text, Length: 44898, dtype: object

In [23]:
y

0        1
1        0
2        1
3        0
4        1
        ..
44893    1
44894    1
44895    1
44896    1
44897    0
Name: label, Length: 44898, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [26]:
x_train.shape

(31428,)

In [27]:
x_test.shape

(13470,)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
vectorization = TfidfVectorizer()

In [30]:
xv_train = vectorization.fit_transform(x_train)

In [31]:
xv_test = vectorization.transform(x_test)

In [32]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6449603 stored elements and shape (31428, 98955)>

In [33]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2758770 stored elements and shape (13470, 98955)>

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [35]:
LR = LogisticRegression()
LR.fit(xv_train, y_train)

LogisticRegression()

In [36]:
pred_lr = LR.predict(xv_test)

In [37]:
LR.score(xv_test, y_test)

0.9851521900519673

In [38]:
def output_label(n):
    if n==0:
        return "Its a Fake News"
    elif n==1:
        return "Its a Real News"

In [1]:
def manual_testing(news):
    # Create a DataFrame from the input news text
    testing_news = {"text": [news]}
    new_def_test = pd.DataFrame(testing_news)
    
    # Apply the wordopt function to preprocess the text
    new_def_test["text"] = new_def_test["text"].apply(textProcessing)
    
    # Vectorize the preprocessed text
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test) 
    
    # Make predictions using the models
    pred_lr = LR.predict(new_xv_test)
    
    # Print each prediction on a separate line
    print("according to our AI model: ")
    print(output_label(pred_lr[0]))

In [ ]:
news_article = str(input())

In [61]:
manual_testing(news_article)

Based on Logistic Regression prediction:
Its a Fake News